[package]
name = "gol"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.89"
js-sys = "0.3.66"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "s"

[dev-dependencies]
wasm-bindgen-test = "0.3.39"
